library(parallel)
library(lhs)

##

#******************************************************
# f <- c(0,1) 
# p_A <- c(0,1)
# N_m <- c(100, 10000)
# N_c <- c(100, 1000)
# alpha <- c(1/6,1/2)
# beta <- c(0,1)
# gamma <- c(2,7)
# mu <- c(1/1095,1/90)
# mu_m <- c(1/35,1/15)

f <- c(0, 1) 
p_A <- c(0, 1)
N_m <- c(100, 50000) #Jen, adjusting the max to 5 mos per host to match Fig. 3. shld discuss
N_c <- c(100, 1000)
alpha <- c(1/6, 1/2)
beta <- c(0, 1)
gamma <- c(2, 7)
mu <- c(1/1095, 1/90)
mu_m <- c(1/35, 1/15)

min <- c(f[1],p_A[1],N_m[1],N_c[1],alpha[1],beta[1],gamma[1],mu[1],mu_m[1])
max <- c(f[2],p_A[2],N_m[2],N_c[2],alpha[2],beta[2],gamma[2],mu[2],mu_m[2])

params <- c("f"
            ,"p_A" 
            ,"N_m"
            ,"N_c"
            ,"alpha"
            ,"beta"
            ,"gamma"
            ,"mu"
            ,"mu_m")

params <- cbind.data.frame(params,min,max)

# # select random sets of parameter values within parameter value ranges
r <- randomLHS(1000,length(params[,1]))
parmVals <- lapply(1:length(params[,1]),function(x){
  temp <- params[x,]
  randomSample <- runif(r[,x],min=temp$min,max=temp$max)
  
})
parmVals <- do.call(cbind.data.frame,parmVals)
names(parmVals) <- params$params

randSnd <- parmVals
randSnd$run <- 1:1000

no_cores <- detectCores() - 1
cl <- makeCluster(no_cores)

sensSims <- parRapply(cl,randSnd,function(x){
 # source(".\\scripts\\r0.R")
  source(".//scripts/r0.R")
  sim.res <- calculate_R0(f=x[1]
                          ,p_A=x[2]
                          ,N_m=x[3]
                          ,N_c=x[4]
                          ,alpha =x[5]
                          ,beta = x[6]
                          ,gamma =x[7]
                          ,mu = x[8]
                          ,mu_m = x[9])
  run <- x[10]
  return(cbind.data.frame(sim.res,run))
  
})

stopCluster(cl)

sensSims <- do.call(rbind,sensSims)
head(sensSims)

dat <- cbind.data.frame(randSnd,sensSims)


dat <- reshape::melt(dat,measure.vars=c("f"
                               ,"p_A" 
                               ,"N_m"
                               ,"N_c"
                               ,"alpha"
                               ,"beta"
                               ,"gamma"
                               ,"mu"
                               ,"mu_m"
))

head(dat)

library(ggplot2)

# ggplot(dat, aes(x=value,y=sim.res)) +
#   geom_point(size=0.01,col="black",alpha=0.2) +
#   facet_wrap(~variable,scales="free_x") +
#   xlab("Parameter value") +
#   ylab("R0") +
#   theme_set(theme_bw())  +
#   theme(panel.border = element_blank()
#         ,axis.line = element_line(color = 'grey')
#         ,text=element_text(size=9)
#         ,panel.spacing = unit(1, "lines")
#         #,plot.margin=unit(c(0.2,0.1,0.1,0.1), "cm")
#         ,axis.text=element_text(size=6)
#         ,legend.key.size = unit(0.6,"line")
#         ,legend.background = element_blank()
#         ,legend.text=element_text(size=9)
#         ,legend.position =c(0.9,0.5)
#         ,legend.title = element_text(size=9)
#         ,strip.background = element_rect(fill="white",color="white")
#   ) 
dat$variable <- factor(dat$variable, levels = c("f", "p_A", "N_m", "N_c", "alpha", "beta", "gamma", "mu", "mu_m"),
       labels = c("f", expression(p[A]), expression(N[m]), expression(N[A]), "alpha", "beta", "gamma", "mu", 
                  expression(mu[m]))
       )
ggplot(dat, aes(x=value, y=sim.res)) +
  geom_point(size=0.3, col="black",alpha=0.5) +
  facet_wrap(~variable, scales="free_x", labeller = label_parsed) +
  xlab("Parameter value") +
  ylab(expression(R[0])) +
  theme_set(theme_bw())  +
  theme(panel.border = element_blank()
        ,axis.line = element_line(color = 'grey')
        ,axis.title=element_text(size=15)
        , strip.text = element_text(size = 20)
        ,panel.spacing = unit(1, "lines")
        #,plot.margin=unit(c(0.2,0.1,0.1,0.1), "cm")
        ,axis.text=element_text(size=14)
        ,strip.background = element_rect(fill="white",color="white")
  ) 


# Use the same parameters generated by Jen to calc species specific R0
# Note we fix, rho_A, N_c = (10, 1000) and vary others
# Jen, should we include the CI around rho_A from binom.test()
speciesSpecificSensDf <- bind_rows(
  expand_grid(mos_sp = paste0("Culex tritaeniorhynchus", " (f = ", f_est$CxT, ")" ), 
              f = f_est$CxT, # estimated fidelity for Cx tritaeniorhynchus
              p_A = 0.05,  # estimated preference for a pis
              N_c = seq(10, 1000, 1),  # starting number of pigs
              parmVals %>% select(-c(f, p_A, N_c)) 
  ),
  expand_grid(mos_sp = paste0("Culex gelidus", " (f = ", f_est$CxG, ")" ), 
              f = f_est$CxG, # estimated fidelity for Cx. gelidus
              p_A = 14/63,  # estimated preference for a pis
              N_c = seq(10, 1000, 1),  # starting number of pigs
              parmVals %>% select(-c(f, p_A, N_c)) 
  ),
  expand_grid(mos_sp = paste0("Culex vishnui", " (f = ", f_est$CxV, ")" ), 
              f = f_est$CxV, # estimated fidelity for Cx Vishnui
              p_A = 2/13,  # estimated preference for a pis
              N_c = seq(10, 1000, 1),  # starting number of pigs
              parmVals %>% select(-c(f, p_A, N_c)) 
  )
) 


sp_R0_list <- mclapply(seq_len(nrow(speciesSpecificSensDf)), function(i){
  calculate_R0(f = speciesSpecificSensDf$f[[i]]
               ,p_A = speciesSpecificSensDf$p_A[[i]]
               ,N_m = speciesSpecificSensDf$N_m[[i]]
               ,N_c = speciesSpecificSensDf$N_c[[i]]
               ,alpha = speciesSpecificSensDf$alpha[[i]]
               ,beta = speciesSpecificSensDf$beta[[i]]
               ,gamma = speciesSpecificSensDf$gamma[[i]]
               ,mu = speciesSpecificSensDf$mu[[i]]
               ,mu_m = speciesSpecificSensDf$mu_m[[i]] )
}, mc.cores = detectCores() - 1 )

speciesSpecificSensDf <- cbind(speciesSpecificSensDf, R0 = unlist(sp_R0_list))

speciesSpecificSensDf %>% 
  group_by(mos_sp, N_c) %>% 
  summarise(meanR0 = mean(R0), 
            uciR0 = Rmisc::CI(R0)[1], 
            lciR0 = Rmisc::CI(R0)[3]) %>% 
  ggplot(aes(x = N_c/Nhost, y = meanR0, fill = mos_sp, colour = mos_sp)) +
  geom_ribbon(aes(ymin = lciR0, ymax = uciR0), alpha = 0.5, colour = NA) +
  geom_line(linewidth = 1.2) +
  scale_x_continuous(breaks = seq(0, 1, 0.2)) +
  scale_y_continuous(n.breaks = 11) +
  scale_colour_brewer(palette = "Set1", direction = 1) +
  scale_fill_brewer(palette = "Set1", direction = 1) +
  labs(x = expression( paste("Proportion of amplifying hosts, pigs (", N[A]/N, ")" ) ), 
       y = expression(paste("Basic reproduction number (", R[0], ")" ) ),  
       color = "Mosquito species", fill = "Mosquito species" ) +
  theme_classic() +
  theme(legend.position = c(0.3, 0.75), #"bottom",
        panel.grid = element_blank(),
        legend.background = element_blank(),
        legend.key.size = unit(1, "cm"),
        axis.text = element_text(colour = "black", size = 12),
        axis.title = element_text(colour = "black", size = 18),
        legend.title = element_text(colour = "black", size = 15),
        legend.text = element_text(colour = "black", face = "bold", size = 15)) 
# ggsave("./ODEModel_with_fidelity/figures/R0_sp.pdf", width = 12, height = 12, units = "in")
